export const BUSINESS_SCHOOL_JOURNALS = [
  "Management Science",
  "Harvard Business Review",
  "MIT Sloan Management Review",
  "California Management Review",
  "Journal of Business Research",
  "Journal of Business Ethics",
  "경영학연구",
  "Academy of Management Review",
  "Academy of Management Journal",
  "Administrative Science Quarterly",
  "Strategic Management Journal",
  "Journal of Management",
  "Personnel Psychology",
  "Journal of Applied Psychology",
  "Organization Science",
  "Organizational Behavior and Human Decision Processes",
  "Journal of Management Studies",
  "Entrepreneurship Theory and Practice",
  "Journal of Organizational Behavior",
  "Human Resource Management",
  "Industrial & Labor Relations Review",
  "Organization Studies",
  "The Leadership Quarterly",
  "인사조직연구",
  "조직과인사관리연구",
  "전략경영연구",
  "산업관계연구",
  "The Accounting Review",
  "Journal of Accounting and Economics",
  "Journal of Accounting Research",
  "Contemporary Accounting Research",
  "Review of Accounting Studies",
  "Accounting, Organisation and Society",
  "Journal of Accounting and Public Policy",
  "Journal of Business, Finance and Accounting",
  "Accounting Horizons",
  "Auditing: A Journal of Practice & Theory",
  "European Accounting Review",
  "Management Accounting Research",
  "Abacus: A Journal of Accounting Finance and Business Studies",
  "Asia-Pacific Journal of Accounting and Economics",
  "Accounting and Finance",
  "Journal of International Financial Management & Accounting",
  "회계저널",
  "회계학연구",
  "회계·세무와감사연구",
  "세무학연구",
  "Journal of Finance",
  "Journal of Financial Economics",
  "Review of Financial Studies",
  "Journal of Financial and Quantitative Analysis",
  "Journal of Banking and Finance",
  "Financial Management",
  "Journal of Corporate Finance",
  "Journal of Empirical Finance",
  "Journal of Financial Markets",
  "Journal of Financial Intermediation",
  "Journal of International Money and Finance",
  "Financial Analyst Journal",
  "Journal of Futures Markets",
  "Journal of Portfolio Management",
  "European Financial Management",
  "Review of Finance",
  "재무연구",
  "한국증권학회지",
  "금융연구",
  "Journal of Marketing Research",
  "Journal of Consumer Research",
  "Marketing Science",
  "Journal of Marketing",
  "Journal of Retailing",
  "Journal of Product Innovation Management",
  "Journal of Consumer Psychology",
  "Journal of the Academy of Marketing Science",
  "International Journal of Research in Marketing",
  "Journal of Interactive Marketing",
  "Industrial Marketing Management",
  "Journal of International Marketing",
  "Journal of Advertising",
  "Psychology & Marketing",
  "Journal of Service Research",
  "International Marketing Review",
  "마케팅연구",
  "소비자학연구",
  "광고학연구",
  "유통연구",
  "MIS Quarterly",
  "Information Systems Research",
  "Journal of Management Information Systems",
  "IEEE Transactions on Engineering Management",
  "Information & Management",
  "Communications of the ACM",
  "Decision Support System",
  "Journal of AIS",
  "Journal of the American Society for Information Science and Technology",
  "International Journal of Electronic Commerce",
  "European Journal of Information Systems",
  "Computers in Human Behavior",
  "Information Systems Journal",
  "Journal of Information Technology",
  "Journal of Strategic Information Systems",
  "APJIS",
  "경영정보학연구",
  "Information Systems Review",
  "지능정보연구",
  "Journal of Operations Management",
  "Operations Research",
  "Decision Sciences",
  "Supply Chain Management: An International Journal",
  "Production and Operations Management",
  "International Journal of Production Economics",
  "European Journal of Operational Research",
  "International Journal of Operations and Production Management",
  "IIE Transactions",
  "International Journal of Production Research",
  "Manufacturing & Service Operations Management",
  "Omega",
  "한국생산관리학회지",
  "경영과학",
  "로지스틱스학연구",
  "Journal of International Business Studies",
  "Journal of World Business",
  "International Journal of Management Reviews",
  "Journal of International Management",
  "Journal of Risk and Uncertainty",
  "British Journal of Management",
  "International Business Review",
  "Management International Review",
  "Journal of Risk and Insurance",
  "Asian Business & Management",
  "Journal of World Trade",
  "European Journal of International Management",
  "Asia Pacific Journal of Management",
  "무역학회지",
  "국제경영연구",
  "무역상무연구"
] as const;

export const BUSINESS_SCHOOL_JOURNAL_SET = new Set(BUSINESS_SCHOOL_JOURNALS.map(normalizeJournalName));

export function normalizeJournalName(value: string): string {
  return value
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/\bthe\b/g, " ")
    .replace(/[^a-z0-9가-힣]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function isBusinessSchoolJournal(value: string): boolean {
  return BUSINESS_SCHOOL_JOURNAL_SET.has(normalizeJournalName(value));
}
